import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar/page";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/Cartcontext";
import Footer from "@/components/ui/footer/page";
import ScrollToTop from "@/components/ui/scroll/page";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import MobileBottomNav from "./(pages)/mobileBottomNav/page";
import { SidebarTrigger } from "@/components/ui/sidebar";
import Mobilenavtop from "./(pages)/Mobilenavtop/page";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      lang="en" suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


<MySessionProvider>
<CartContextProvider>

<Navbar/>
   {children}
   <ScrollToTop/>
       <Toaster />
     
<Footer/>
<MobileBottomNav />
</CartContextProvider>

</MySessionProvider>


      </body>
    </html>
  );
}
